name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  easy_localization: ^3.0.6
  shared_preferences: ^2.0.15
  auto_route: ^7.8.4
  fpdart: ^1.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.2

flutter:
  assets:
    - assets/translations/
