// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_JWj5tiENOid4DRyXCYIcWdfLvRTeWUQ',
    appId: '1:890034566376:web:1904748f54b078b144c55d',
    messagingSenderId: '890034566376',
    projectId: 'fitness-app-f4ef3',
    authDomain: 'fitness-app-f4ef3.firebaseapp.com',
    storageBucket: 'fitness-app-f4ef3.appspot.com',
    measurementId: 'G-VMW3N3VE23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNKP-BMy4PMWKhqlDfMN2bmajuYIdhZ6U',
    appId: '1:890034566376:android:696482ff723fbe0144c55d',
    messagingSenderId: '890034566376',
    projectId: 'fitness-app-f4ef3',
    storageBucket: 'fitness-app-f4ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFpe7XtMkX3omxyWYPGX9d1oeeWLm3z8',
    appId: '1:890034566376:ios:73c70c9f0e51940944c55d',
    messagingSenderId: '890034566376',
    projectId: 'fitness-app-f4ef3',
    storageBucket: 'fitness-app-f4ef3.appspot.com',
    androidClientId: '890034566376-rfi7pvnh3q373sa413iqnm41q4bimjm9.apps.googleusercontent.com',
    iosClientId: '890034566376-fg1h4hpud0tc6uo5gdi0grcmqk1pagoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProProject',
  );
}
