// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB94D4fBiPXtNNaK_F-fO_vz0Ez7LlYaLI',
    appId: '1:441716782635:web:f9224e7fc765fb4a781c6e',
    messagingSenderId: '441716782635',
    projectId: 'fitness-app-3de03',
    authDomain: 'fitness-app-3de03.firebaseapp.com',
    storageBucket: 'fitness-app-3de03.appspot.com',
    measurementId: 'G-4LJE2S93WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnRpVu_Kt8JYJZQiONJaou-B814OJcDm0',
    appId: '1:441716782635:android:333160bcb76f4eed781c6e',
    messagingSenderId: '441716782635',
    projectId: 'fitness-app-3de03',
    storageBucket: 'fitness-app-3de03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVp0LMiYtE2r7OjCgy9oa9CqofhMGKKQ',
    appId: '1:441716782635:ios:37b1bea649422c26781c6e',
    messagingSenderId: '441716782635',
    projectId: 'fitness-app-3de03',
    storageBucket: 'fitness-app-3de03.appspot.com',
    iosClientId: '441716782635-hhvsni4mgtq4a7kaougegqjpsu9jv1h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProProject',
  );
}
