name: fistness_app_firebase
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: ^4.0.3
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  fpdart: ^1.1.0
  google_fonts: ^4.0.4
  json_annotation: ^4.7.0
  lottie: ^2.3.2
  syncfusion_flutter_gauges: ^21.2.4
  video_player: ^2.4.10
  youtube_player_flutter: ^8.1.1
  shimmer: ^3.0.0
  easy_localization: ^3.0.6
  flutter_gen: ^5.4.0
  very_good_analysis: ^5.1.0
  mockito: ^5.4.4
  #packages
  core:
    path: modules/core
  ui_kit:
    path: modules/ui_kit

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.5.4
  envied_generator: ^0.5.4+1
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    lottie: true
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/png/
    - assets/icon/
