name: fistness_app_firebase
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.0.3
  dio: ^5.1.2
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.0.8
  fpdart: ^1.1.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  json_annotation: ^4.7.0
  lottie: ^2.3.2
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.15
  syncfusion_flutter_gauges: ^21.2.4
  video_player: ^2.4.10
  youtube_player_flutter: ^8.1.1
  shimmer: ^3.0.0
  easy_localization: ^3.0.6
  flutter_gen: ^5.4.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.5.4
  envied_generator: ^0.5.4+1
  dependency_validator: ^3.0.0

flutter_gen:
  integrations:
    lottie: true
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/png/
    - assets/translations/
    - assets/icon/
